//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CitizensGenerator
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EGovernmentEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EGovernmentEntities object using the connection string found in the 'EGovernmentEntities' section of the application configuration file.
        /// </summary>
        public EGovernmentEntities() : base("name=EGovernmentEntities", "EGovernmentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EGovernmentEntities object.
        /// </summary>
        public EGovernmentEntities(string connectionString) : base(connectionString, "EGovernmentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EGovernmentEntities object.
        /// </summary>
        public EGovernmentEntities(EntityConnection connection) : base(connection, "EGovernmentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCitizen> tblCitizen
        {
            get
            {
                if ((_tblCitizen == null))
                {
                    _tblCitizen = base.CreateObjectSet<tblCitizen>("tblCitizen");
                }
                return _tblCitizen;
            }
        }
        private ObjectSet<tblCitizen> _tblCitizen;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCitizen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCitizen(tblCitizen tblCitizen)
        {
            base.AddObject("tblCitizen", tblCitizen);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EGovernmentModel", Name="tblCitizen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCitizen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCitizen object.
        /// </summary>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="nationalNumber">Initial value of the NationalNumber property.</param>
        /// <param name="birthday">Initial value of the Birthday property.</param>
        /// <param name="birthPlace">Initial value of the BirthPlace property.</param>
        /// <param name="amana">Initial value of the Amana property.</param>
        /// <param name="kiedPlace">Initial value of the KiedPlace property.</param>
        /// <param name="kiedNumber">Initial value of the KiedNumber property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="socialStatus">Initial value of the SocialStatus property.</param>
        /// <param name="religion">Initial value of the Religion property.</param>
        public static tblCitizen CreatetblCitizen(global::System.String firstName, global::System.String lastName, global::System.String nationalNumber, global::System.String birthday, global::System.String birthPlace, global::System.String amana, global::System.String kiedPlace, global::System.String kiedNumber, global::System.String gender, global::System.String socialStatus, global::System.String religion)
        {
            tblCitizen tblCitizen = new tblCitizen();
            tblCitizen.FirstName = firstName;
            tblCitizen.LastName = lastName;
            tblCitizen.NationalNumber = nationalNumber;
            tblCitizen.Birthday = birthday;
            tblCitizen.BirthPlace = birthPlace;
            tblCitizen.Amana = amana;
            tblCitizen.KiedPlace = kiedPlace;
            tblCitizen.KiedNumber = kiedNumber;
            tblCitizen.Gender = gender;
            tblCitizen.SocialStatus = socialStatus;
            tblCitizen.Religion = religion;
            return tblCitizen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FatherNationalNumber
        {
            get
            {
                return _FatherNationalNumber;
            }
            set
            {
                OnFatherNationalNumberChanging(value);
                ReportPropertyChanging("FatherNationalNumber");
                _FatherNationalNumber = StructuralObject.SetValidValue(value, true, "FatherNationalNumber");
                ReportPropertyChanged("FatherNationalNumber");
                OnFatherNationalNumberChanged();
            }
        }
        private global::System.String _FatherNationalNumber;
        partial void OnFatherNationalNumberChanging(global::System.String value);
        partial void OnFatherNationalNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MotherNationalNumber
        {
            get
            {
                return _MotherNationalNumber;
            }
            set
            {
                OnMotherNationalNumberChanging(value);
                ReportPropertyChanging("MotherNationalNumber");
                _MotherNationalNumber = StructuralObject.SetValidValue(value, true, "MotherNationalNumber");
                ReportPropertyChanged("MotherNationalNumber");
                OnMotherNationalNumberChanged();
            }
        }
        private global::System.String _MotherNationalNumber;
        partial void OnMotherNationalNumberChanging(global::System.String value);
        partial void OnMotherNationalNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NationalNumber
        {
            get
            {
                return _NationalNumber;
            }
            set
            {
                if (_NationalNumber != value)
                {
                    OnNationalNumberChanging(value);
                    ReportPropertyChanging("NationalNumber");
                    _NationalNumber = StructuralObject.SetValidValue(value, false, "NationalNumber");
                    ReportPropertyChanged("NationalNumber");
                    OnNationalNumberChanged();
                }
            }
        }
        private global::System.String _NationalNumber;
        partial void OnNationalNumberChanging(global::System.String value);
        partial void OnNationalNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value, false, "Birthday");
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private global::System.String _Birthday;
        partial void OnBirthdayChanging(global::System.String value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BirthPlace
        {
            get
            {
                return _BirthPlace;
            }
            set
            {
                OnBirthPlaceChanging(value);
                ReportPropertyChanging("BirthPlace");
                _BirthPlace = StructuralObject.SetValidValue(value, false, "BirthPlace");
                ReportPropertyChanged("BirthPlace");
                OnBirthPlaceChanged();
            }
        }
        private global::System.String _BirthPlace;
        partial void OnBirthPlaceChanging(global::System.String value);
        partial void OnBirthPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Amana
        {
            get
            {
                return _Amana;
            }
            set
            {
                OnAmanaChanging(value);
                ReportPropertyChanging("Amana");
                _Amana = StructuralObject.SetValidValue(value, false, "Amana");
                ReportPropertyChanged("Amana");
                OnAmanaChanged();
            }
        }
        private global::System.String _Amana;
        partial void OnAmanaChanging(global::System.String value);
        partial void OnAmanaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KiedPlace
        {
            get
            {
                return _KiedPlace;
            }
            set
            {
                OnKiedPlaceChanging(value);
                ReportPropertyChanging("KiedPlace");
                _KiedPlace = StructuralObject.SetValidValue(value, false, "KiedPlace");
                ReportPropertyChanged("KiedPlace");
                OnKiedPlaceChanged();
            }
        }
        private global::System.String _KiedPlace;
        partial void OnKiedPlaceChanging(global::System.String value);
        partial void OnKiedPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KiedNumber
        {
            get
            {
                return _KiedNumber;
            }
            set
            {
                OnKiedNumberChanging(value);
                ReportPropertyChanging("KiedNumber");
                _KiedNumber = StructuralObject.SetValidValue(value, false, "KiedNumber");
                ReportPropertyChanged("KiedNumber");
                OnKiedNumberChanged();
            }
        }
        private global::System.String _KiedNumber;
        partial void OnKiedNumberChanging(global::System.String value);
        partial void OnKiedNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true, "Image");
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SocialStatus
        {
            get
            {
                return _SocialStatus;
            }
            set
            {
                OnSocialStatusChanging(value);
                ReportPropertyChanging("SocialStatus");
                _SocialStatus = StructuralObject.SetValidValue(value, false, "SocialStatus");
                ReportPropertyChanged("SocialStatus");
                OnSocialStatusChanged();
            }
        }
        private global::System.String _SocialStatus;
        partial void OnSocialStatusChanging(global::System.String value);
        partial void OnSocialStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Religion
        {
            get
            {
                return _Religion;
            }
            set
            {
                OnReligionChanging(value);
                ReportPropertyChanging("Religion");
                _Religion = StructuralObject.SetValidValue(value, false, "Religion");
                ReportPropertyChanged("Religion");
                OnReligionChanged();
            }
        }
        private global::System.String _Religion;
        partial void OnReligionChanging(global::System.String value);
        partial void OnReligionChanged();

        #endregion

    }

    #endregion

}
